### ISSUE TITLE
[GCI-2018] Improvements in README and code

### ISSUE THREAD

**Issue by Yash-Garg** [scorelab/Massa#31]
- The `README.md` file does not contain sufficient information on how to run the app. The documentation should be improved in order for newbies.

- Block Allocation is not proper when New User is created. It gets a new ID but merging is not done. This can be fixed by `goto` and going to the ID Label.

- On `line 20`, the margin given is 14. This can be changed upto 16 in order to get a better view.

- Also at `line 17` exportation of Module can be done of any specific object as it can cause multiple issues and then crashing of the application.

- Also there should be an **Pre-Loaded environment** that can be used to run Python/Angular Bash GUI in Windows/Mac without getting issues.

**Comment by swatisingh45** [comment]
@Yash-Garg please explain in detail what is not mentioned in `README.md`

**Comment by Yash-Garg** [comment]
@swatisingh45 My bad i didn't saw the **Refer to Wiki** line ! Wiki has everything stated properly.
