### ISSUE TITLE
Google Docs Sharing Link Permission

### ISSUE THREAD

**Issue by acp** [scorelab/Massa#35]
It has come to my attention that the google docs file doesn't actually have anything in it. I can edit the content, change the name of the file, and many more things.

Advice : Change the permission on the google docs sharing link to **Viewing** instead of **Editing**.

**Comment by acp** [comment]
The doc link : https://docs.google.com/document/d/1Z7jk5WzJ2_wMt0_riYiB6q5hmrhU_Uybod42j_cXJAE/edit

**Comment by JaDogg** [comment]
Good catch. Fortunately you I can view all the history. 🤔

**Comment by JaDogg** [comment]
Will close once link is fixed to view only
