### ISSUE TITLE
Interface mockups

### ISSUE THREAD

**Issue by padamchopra** [scorelab/Massa#4]
I've created the following mockups for the Massa app. If this is ok, I can implement it using react native and make a PR. A working demo is available [here](https://marvelapp.com/48hah41)

I already have a version with splash screen implemented available [here](http://github.com/padamchopra/Massa/), should I create a PR for this only?
# **Screenshots**
### Splash Screen
<img src="https://user-images.githubusercontent.com/19776024/35169579-0930f084-fd83-11e7-93b4-1b69a3a08a9a.png" height="500"><br/>
### Login
<img src="https://user-images.githubusercontent.com/19776024/35169638-3e9a6818-fd83-11e7-8ad2-76f9ca8d3af5.png" height="500"><br/>
### Downloads
<img src="https://user-images.githubusercontent.com/19776024/35169837-0fdd5340-fd84-11e7-8855-82b3dc620f52.png" height="500"><br/>
### Download Details
<img src="https://user-images.githubusercontent.com/19776024/35169865-24d85f42-fd84-11e7-80c1-effaf8ed0b85.png" height="500"><br/>
### About Screen
<img src="https://user-images.githubusercontent.com/19776024/35169894-387d03fe-fd84-11e7-9455-8c4f51720edb.png" height="500">

**Comment by iammosespaulr** [comment]
How do you plan on retrieving the code from MarvelApps ??? 
Nice Job btw :smile:

**Comment by padamchopra** [comment]
@iammosespaulr I already have the code written for react :P 
I'll make a PR after the name and logo have been finalised

**Comment by JaDogg** [comment]
@padamchopra Well done.
